### ISSUE TITLE
Features Visualization

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/Heritage-Housing-Prediction#3]
**Acceptance Criteria**:
Each features should be plot and compare with SalePrice as target.

**Tasks**:
- [ ] Create a new Jupiter Notebook
- [ ] Plot the SalePrice distribution
- [ ] Plot the SalePrice against all other features
